name: Unit Testing

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  LinuxConda:
    runs-on: ubuntu-latest
    env:
      CONDA_ALWAYS_YES: 1
      VTK_VERSION: 8.2
      conda_env: pyvista-vtk8.2
      DISPLAY: ':99.0'
      PYVISTA_OFF_SCREEN: True

    steps:
      - uses: actions/checkout@v2

      - name: Install headless display
        run: |
          .ci/install.sh
      - name: Create Anaconda environment
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda config --add channels conda-forge
          sed -i -e 's/- vtk$/- vtk= ${{ env.VTK_VERSION }} /' environment.yml
          conda env create --quiet -n ${{ env.conda_env }} --file environment.yml
          conda activate ${{ env.conda_env }}
          conda list
      - name: Install Helios
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate ${{ env.conda_env }}
          pip install -e .
          which python
          pip install flake8 pytest
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          python -c "import helios; print('Helios :', helios.__version__)"
      - name: Test Core API
        continue-on-error: true
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate ${{ env.conda_env }}
          pytest -svv